Update props for SEO component
cesko-digital/movapp pull request #214
Opened 2022-12-11 12:35 UTC by kubahasek

2022-12-18 12:37 UTC, JuroUhlar requested changes

2022-12-18 12:37 UTC, JuroUhlar commented on components/basecomponents/SEO.tsx
> +      <meta name="description" content={description ? description : title} />
Try this instead: `description ?? title` :) 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2022-12-18 12:37 UTC, JuroUhlar commented on components/basecomponents/SEO.tsx
> +      <meta name="description" content={description ? description : title} />
Also, just assign it to a variable and re-use it: 

`const appliedDescription = description ?? title;`

and then 

` <meta name="og:description" content={appliedDescription} />`

2022-12-18 12:39 UTC, JuroUhlar commented on components/basecomponents/SEO.tsx
> +const SEO = ({ title, description, image = 'https://www.movapp.cz/icons/movapp-cover.jpg', noreferrer = true }: Props) => {
You can also see all uses of `SEO` and remove the `image` prop if it contains the default value :)

2023-01-08 18:02 UTC, JuroUhlar commented
@kubahasek Nice, can you resolve the merge conflict please so we can merge it? Thanks a lot! :)

2023-01-08 18:13 UTC, kubahasek commented
@JuroUhlar Conflict fixed! :)

2023-01-23 00:03 UTC, JuroUhlar approved these changes

2023-01-23 00:05 UTC, merged