Fix image sizes
cesko-digital/movapp pull request #233
Opened 2023-01-30 14:32 UTC by kubahasek

2023-01-30 14:45 UTC, jejdacz requested changes

2023-01-30 14:45 UTC, jejdacz commented on components/basecomponents/MemoryGame/MemoryGameCard.tsx
> +            <Image src={cardBackImage} layout="fill" objectFit="cover" alt="card back" priority />
tady zrovna může zrovna být 25vw

2023-01-30 14:45 UTC, jejdacz commented on components/basecomponents/MemoryGame/MemoryGameCard.tsx
>                layout="fill"
tady zrovna může zrovna být 25vw

2023-01-31 17:46 UTC, jejdacz approved these changes

2023-01-31 17:47 UTC, jejdacz approved these changes

2023-01-31 17:48 UTC, jejdacz approved these changes
OK..good job

2023-01-31 17:53 UTC, kubahasek commented
Should I merge?

2023-01-31 18:09 UTC, jejdacz commented
I wanted to test it first. Tomorrow.

2023-02-01 08:52 UTC, merged