Updating plausible
cesko-digital/movapp pull request #326
Opened 2023-06-29 13:53 UTC by filiptaticek

- Moving the Plausible logic from ActionButton to its onClick attribute
- Adding Plausible to button from dictionary as well as from button restarting the exercise
- Changing useCountryVariant to useLanguage

2023-06-29 20:08 UTC, jejdacz requested changes
Rozhodně bych zkusil udělat pro tracking custom hook kam si nainportuju vše co potřebuji. tj. useLanguage , usePlausible, z useExerciseStore všechny potřebné props, ukončení hry pohlídám v useEffect sledováním storeStaus. Z hooku ven si pošlu upravenou metodu do které už nemusím tím pádem zadávat language, numberofcorrectanswers, lengthofexercise prostě už potřebuju jen název eventu. A lze to udělat i tak že pošlu ven objekt tracking který bude mít metody exerciseStarted, exerciseFinished atd. tím pádem už nemusím navenek znát ani názvy eventů a budu je mít pěkně v tom hooku na jednom místě a zároveň mi to může pomoct s otypováním metod v Typescript když každá metoda vyžaduje jiné props.

2023-06-30 05:28 UTC, filiptaticek commented on components/basecomponents/Exercise/exerciseStore.ts
> +  const nextExercise = (plausible: Plausible, language: Language) => {
Jo, chápu, asi jsem trochu přecenil své síly, když jsem se rozhodl zasahovat do souborů, kde jsou ta cvičení. Zkusím to odpoledne udělat podle toho, jak říkáš, a případně bych ti to přenechal.

2023-06-30 05:44 UTC, jejdacz commented on components/basecomponents/Exercise/exerciseStore.ts
> +  const nextExercise = (plausible: Plausible, language: Language) => {
Ale neboj to zvládneš, s tím custom hookem tě ty soubory ani nemusí trápit, stačí jen sledovat stav té aplikace, napadá mě že by tím šel spouštět i začátek toho cvičení a nemuselo by to být vůbec spojeno s tlačítkem.

2023-06-30 15:58 UTC, filiptaticek commented on components/basecomponents/Exercise/exerciseStore.ts
> +  const nextExercise = (plausible: Plausible, language: Language) => {
Ok, ten custom hook se teda podívá, zda už je cvičení hotové, a v tu chvíli do plausible pošle exerciseFinished. Ale v jaký moment to tam má poslat exerciseStarted?

2023-06-30 16:15 UTC, met commented
@filiptaticek Když s tim experimentuješ delší dobu, bylo by lepší, kdybys posílal během těch experimentů radši událost TestEvent. 
Protože události s finálnim názvem na web už jsou, snažim se je sledovat. Ale teď neodliším kolik z toho naměřeného jsou být tvoje lokální testy. Zkus ty finálni názvy eventů nechat na produkční web a pro vývoj použivat ten testovací prosim.

2023-06-30 16:16 UTC, jejdacz commented on components/basecomponents/Exercise/exerciseStore.ts
> +  const nextExercise = (plausible: Plausible, language: Language) => {
no bude to muset hlídat změnu na stav active myslím, píšu to teď jen z telefonu po třech pivech ,ale mrkni jaký stavy může mít to exercise store a ještě lze hlídat i jestli exercice přešlo z null na něco jiného

2023-06-30 16:17 UTC, filiptaticek commented
> @filiptaticek Když s tim experimentuješ delší dobu, bylo by lepší, kdybys posílal během těch experimentů radši událost TestEvent. Protože události s finálnim názvem na web už jsou, snažim se je sledovat. Ale teď neodliším kolik z toho naměřeného jsou být tvoje lokální testy. Zkus ty finálni názvy eventů nechat na produkční web a pro vývoj použivat ten testovací prosim.
 


> @filiptaticek Když s tim experimentuješ delší dobu, bylo by lepší, kdybys posílal během těch experimentů radši událost TestEvent. Protože události s finálnim názvem na web už jsou, snažim se je sledovat. Ale teď neodliším kolik z toho naměřeného jsou být tvoje lokální testy. Zkus ty finálni názvy eventů nechat na produkční web a pro vývoj použivat ten testovací prosim.

Ok, to dává smysl, budu na to myslet Martine

2023-07-01 07:33 UTC, filiptaticek commented
@jejdacz  už se asi blížím tvé vizi, jen mám ještě problém v tom, že to exerciseFinished to aktuálně zaregistruje dvakrát na konci cvičení, a když to spustím ze slovníčku, tak to taky zaregistruje dvakrát. Psal jsem to do komentáře k tomu commitu, ale vynechal jsem slovo ,,twice" omylem.

2023-07-04 05:51 UTC, jejdacz commented
solved in https://github.com/cesko-digital/movapp/pull/327

2023-07-04 05:51 UTC, closed without merging