add search tracking
cesko-digital/movapp pull request #363
Opened 2023-09-16 17:32 UTC by nataliadiak

2023-09-16 17:47 UTC, met commented
Thanks. Funcionality is perfect. Just wait for the codereview from @jejdacz and after that merge it.

2023-09-17 12:49 UTC, jejdacz commented
I want to test it a bit I'm not familiar with this part of code. BTW what the SEARCH BUTTON do? It has no onclick function?

2023-09-17 13:23 UTC, nataliadiak commented
@jejdacz I think we don't need this button. We can replace it by non-clickable search icon.

2023-09-17 13:50 UTC, met commented
Please, do not change Search button now. Only when we have feedback from UX search, that we need to change it.

2023-09-17 14:07 UTC, nataliadiak commented
> Please, do not change Search button now. Only when we have feedback from UX search, that we need to change it.

Fine, it is just a side note.

2023-09-21 06:08 UTC, jejdacz requested changes
Soubor useTracking.ts nemůže zůstat v /pages ... není to page. Kvůli tomu to také Vercel nenasadí. Navrhuji přesunout do /components/hooks/useDictionarySearchTracking.ts.

Teď sledujeme pouze jestli uživatel vůbec při návštěvě slovníčku použije vyhledávání. Pokud je toto v pořádku stačí provést pouze úpravu výše.

Krásná práce, díky.

2023-09-21 07:36 UTC, nataliadiak commented
> Soubor useTracking.ts nemůže zůstat v /pages ... není to page. Kvůli tomu to také Vercel nenasadí. Navrhuji přesunout do /components/hooks/useDictionarySearchTracking.ts.
> 
> Teď sledujeme pouze jestli uživatel vůbec při návštěvě slovníčku použije vyhledávání. Pokud je toto v pořádku stačí provést pouze úpravu výše.
> 
> Krásná práce, díky.

Děkuji za poznámku, nevšimla jsem si toho, soubor přesunu.

2023-09-21 15:37 UTC, jejdacz approved these changes
Goood job.

2023-09-21 22:03 UTC, merged