exclude from sitemap
cesko-digital/movapp pull request #371
Opened 2023-10-20 14:43 UTC by Andrea-Prague

2023-10-20 15:20 UTC, met requested changes

2023-10-20 15:20 UTC, met commented on next-sitemap.config.js
> +  cs: ['/exercise/re*', '/uk/exercise/re*', ' /kiosk/*', '/uk/kiosk/*', ...PDF_LINKS],
Namísto `' /kiosk/*', '/uk/kiosk/*'` bude třeba `'/kiosk*', '/uk/kiosk*'`
(bez mezery na začátku a konečného lomítka), stejně tak u polské a slovenské verze:

2023-10-20 16:19 UTC, nataliadiak commented
@Andrea-Prague  `exclude` nepodporuje regex, bohužel, viz dokumentace https://www.npmjs.com/package/next-sitemap
`transform `už ano,  pak by to vyloučilo pdf stránky, které zmiňuje Martin.
mělo by stačit přidat ještě:
```
transform: async (_, routes) => routes.filter(route => !pattern.test(route.url))
```

2023-10-20 17:19 UTC, met commented
> @Andrea-Prague `exclude` nepodporuje regex, bohužel, viz dokumentace https://www.npmjs.com/package/next-sitemap `transform `už ano.

aha, tak to bude důvod, proč teď nezafungovalo to PDF_LINKS a jsou ty pdf adresy ve výstupu.

Zatím těch hvězdičkových filtrů není tolik, aby vadilo je takhle ručně všechny vypsat. A strukturu URL neměníme tak často, abychom je nestíhali updatovat. Tak to zkusme s nimi, pokud to nejde líp.

2023-10-25 16:01 UTC, nataliadiak commented on next-sitemap.config.js
> +  '/pdf/.gitkeep'
Stále je tam pdf/.gitkeep, mohla bys prosím ověřit, jestli tečka má také speciální význam, libovolný znak? Pokud ano, tak ji můžeme escapovat.

2023-10-25 18:48 UTC, met commented
@Andrea-Prague Skvělé, tohle je supr.


Zbyl tam ten divný `/pdf/.gitkeep` - kdybys rychle přišla na to, jak se ho zbavit, zbav se ho. Kdybys nenašla snadnou cestu , můžeme to mergnou i takhle a tímhle posledním malým problémem se netrápit.  

Nechápu, proč to s tečkou nebere, podle mě to máš správně, můžeš zkusit i agresivnější vzor `'/pdf/*gitkeep'` nebo `'*gitkeep'` to by nám nemělo vadit.

2023-10-31 10:47 UTC, met requested changes
Díky, sitemapa teď vypadá super, můžeme mergnout.

Jen prosím tu úpravu workflows/automated-tests.yml hoďme do samostatného PR, nemíchejme ji do tohodle, kam nepatří.

2023-10-31 11:54 UTC, met approved these changes
👍 let's merge it

2023-10-31 22:21 UTC, merged