add component RandomStoryList and new common data
cesko-digital/movapp pull request #372
Opened 2023-10-22 22:54 UTC by daria31v

2023-10-23 09:14 UTC, met commented
@daria31v On big screen this looks good. But not on small screens. Try in Chrome to simulate mobile devices and you will see it https://developer.chrome.com/docs/devtools/device-mode/ Probably needs just a little of CSS polishing.

2023-11-17 21:27 UTC, nataliadiak approved these changes

2023-11-22 12:50 UTC, met requested changes
Hi, I see two problems here:
- in Slovak web version it suggest fairytales that are not available in Slovak language
- there is problem with picture responsibility. On some screen with it looks good, on some not. Here screenshot. Try to change browser window width and you will see it too.

![image](https://github.com/cesko-digital/movapp/assets/59498/68ccb34f-5a49-493d-8e87-03cc617ceeca)

2023-11-23 19:09 UTC, met commented
Closing this due to conflicts. Continuing in a new PR https://github.com/cesko-digital/movapp/pull/376

2023-11-23 19:09 UTC, closed without merging